### ISSUE TITLE
CloudRun configuration for skaffold requires `projectid` and therefore cannot be generic for deployment

### ISSUE THREAD

**Issue by evekhm** [GoogleCloudPlatform/solutions-template#158]
The skaffold yaml file for Cloud Run requires setting of the projectid.

Currently when using solutions-builder for CloudRun configuration in the generated skaffold.yaml is hardcoded. When you make this value `your-project-id` the `sb set project-id` command would not replace the value.

```
- &cloudrun-profile # YAML anchor used by "default" profile.
  name: cloudrun
  manifests:
    rawYaml:
      - manifests/cloudrun-service.yaml
  deploy:
    cloudrun:
      region: us-central1
      projectid: your-project-id
```

Therefore you cannot have a template that everyone can deploy into their own GCP environment.

The only workaround is to use manual command instead of the `sb deploy`:

`skaffold run -p default-deploy  -n default --default-repo="gcr.io/$PROJECT_ID" --cloud-run-project=$PROJECT_ID --cloud-run-location=us-central1`
