### ISSUE TITLE
skaffold does not do deploy step when using skaffold version: v2.0.1

### ISSUE THREAD

**Issue by evekhm** [GoogleCloudPlatform/solutions-template#21]
If you run:
`skaffold run -p prod --default-repo=gcr.io/${PROJECT_ID}`

Build is done, but no deploy step. Reason is the skaffold.yaml file for sample-service needs to be upgraded. 

Instead of:
```
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
```

I have tried the following fix to get to deployment (when using apiVersion: `skaffold/v3` ):

```
  deploy:
    kubectl: { }
  manifests:
    kustomize:
      paths:
      - ./kustomize/prod
```
